source "https://rubygems.org"

gem "fastlane", "~> 2.227"
gem "cocoapods", "~> 1.16"

# Loaded plugins for both Android and iOS lanes.
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
