// Generates GetX locale bindings from JSON locale files.
//
// Output matches the shape used by this repo:
// - AppTranslation.translations (locale -> map)
// - LocaleKeys.<flattened_key> constants
// - Locales.<locale> maps
//
// Usage:
// dart run scripts/i18n/generate_getx_locales.dart \
//   --locales-dir packages/bear_necessities/assets/locales \
//   --output packages/bear_necessities/lib/generated/locales.g.dart
//
import 'dart:convert';
import 'dart:io';

final _placeholderRe = RegExp(r'%[A-Za-z0-9_]+%');

void main(List<String> args) {
  final parsed = _parseArgs(args);
  final localesDir = Directory(parsed.localesDir);
  if (!localesDir.existsSync()) {
    stderr.writeln('Locales dir not found: ${localesDir.path}');
    exitCode = 2;
    return;
  }

  final localeFiles =
      localesDir
          .listSync()
          .whereType<File>()
          .where((f) => f.path.toLowerCase().endsWith('.json'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));

  if (localeFiles.isEmpty) {
    stderr.writeln('No .json files found in ${localesDir.path}');
    exitCode = 2;
    return;
  }

  final localeToFlat = <String, Map<String, String>>{};
  for (final file in localeFiles) {
    final locale = _basenameNoExt(file.path);
    final decoded = jsonDecode(file.readAsStringSync());
    if (decoded is! Map<String, dynamic>) {
      stderr.writeln('Locale file must be a JSON object: ${file.path}');
      exitCode = 2;
      return;
    }
    final flat = <String, String>{};
    _flattenJson(decoded, const [], flat);
    localeToFlat[locale] = flat;
  }

  final referenceLocale =
      parsed.referenceLocale ?? _pickReference(localeToFlat);
  final reference = localeToFlat[referenceLocale];
  if (reference == null) {
    stderr.writeln(
      "Reference locale '$referenceLocale' not found. Found: ${localeToFlat.keys.join(', ')}",
    );
    exitCode = 2;
    return;
  }

  // Validate key coverage and placeholders across locales.
  final refKeys = reference.keys.toSet();
  for (final entry in localeToFlat.entries) {
    final locale = entry.key;
    final flat = entry.value;
    final keys = flat.keys.toSet();
    final missing = refKeys.difference(keys).toList()..sort();
    final extra = keys.difference(refKeys).toList()..sort();

    if (missing.isNotEmpty || extra.isNotEmpty) {
      stderr.writeln('Key mismatch for locale $locale:');
      if (missing.isNotEmpty) {
        stderr.writeln('  Missing (${missing.length}): ${missing.join(', ')}');
      }
      if (extra.isNotEmpty) {
        stderr.writeln('  Extra (${extra.length}): ${extra.join(', ')}');
      }
      exitCode = 2;
      return;
    }

    for (final k in refKeys) {
      final refVal = reference[k] ?? '';
      final val = flat[k] ?? '';
      final refPh = _placeholders(refVal);
      final ph = _placeholders(val);
      if (!_listEquals(refPh, ph)) {
        stderr.writeln('Placeholder mismatch for key $k in $locale');
        stderr.writeln('  expected: $refPh');
        stderr.writeln('  got:      $ph');
        exitCode = 2;
        return;
      }
    }
  }

  // Build a stable, deterministic key order (based on reference).
  final orderedKeys = refKeys.toList()..sort();

  final outFile = File(parsed.outputPath);
  outFile.parent.createSync(recursive: true);
  outFile.writeAsStringSync(_renderDart(localeToFlat, orderedKeys));
  stdout.writeln('Wrote ${outFile.path}');
}

void _flattenJson(
  Map<String, dynamic> obj,
  List<String> prefix,
  Map<String, String> out,
) {
  final keys = obj.keys.toList()..sort();
  for (final key in keys) {
    final value = obj[key];
    final nextPrefix = [...prefix, key];
    if (value is Map<String, dynamic>) {
      _flattenJson(value, nextPrefix, out);
      continue;
    }
    if (value is Map) {
      // If it's a Map<dynamic,dynamic>, normalize.
      final normalized = <String, dynamic>{};
      value.forEach((k, v) {
        normalized[k.toString()] = v;
      });
      _flattenJson(normalized, nextPrefix, out);
      continue;
    }
    final flatKey = nextPrefix.join('_');
    out[flatKey] = value?.toString() ?? '';
  }
}

String _renderDart(
  Map<String, Map<String, String>> localeToFlat,
  List<String> keys,
) {
  final locales = localeToFlat.keys.toList()..sort();

  final b = StringBuffer();
  b.writeln(
    '// DO NOT EDIT. This is code generated by scripts/i18n/generate_getx_locales.dart',
  );
  b.writeln('');
  b.writeln('// ignore_for_file: lines_longer_than_80_chars');
  b.writeln('// ignore: avoid_classes_with_only_static_members');
  b.writeln('class AppTranslation {');
  b.writeln('  static Map<String, Map<String, String>> translations = {');
  for (final loc in locales) {
    b.writeln("    '$loc': Locales.$loc,");
  }
  b.writeln('  };');
  b.writeln('}');
  b.writeln('');

  b.writeln('class LocaleKeys {');
  b.writeln('  LocaleKeys._();');
  for (final k in keys) {
    final ident = k; // already underscore-safe
    b.writeln("  static const $ident = '$k';");
  }
  b.writeln('}');
  b.writeln('');

  b.writeln('class Locales {');
  for (final loc in locales) {
    b.writeln('  static const $loc = {');
    final flat = localeToFlat[loc]!;
    for (final k in keys) {
      final v = flat[k] ?? '';
      // jsonEncode returns a valid Dart string literal (double-quoted).
      b.writeln("    '$k': ${jsonEncode(v)},");
    }
    b.writeln('  };');
    b.writeln('');
  }
  b.writeln('}');
  return b.toString();
}

List<String> _placeholders(String s) {
  final set = <String>{};
  for (final m in _placeholderRe.allMatches(s)) {
    set.add(m.group(0)!);
  }
  final list = set.toList()..sort();
  return list;
}

bool _listEquals<T>(List<T> a, List<T> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}

String _basenameNoExt(String path) {
  final name = path.split(Platform.pathSeparator).last;
  final dot = name.lastIndexOf('.');
  return dot == -1 ? name : name.substring(0, dot);
}

String _pickReference(Map<String, Map<String, String>> localeToFlat) {
  if (localeToFlat.containsKey('en_GB')) return 'en_GB';
  return (localeToFlat.keys.toList()..sort()).first;
}

({String localesDir, String outputPath, String? referenceLocale}) _parseArgs(
  List<String> args,
) {
  String? localesDir;
  String? outputPath;
  String? referenceLocale;

  for (var i = 0; i < args.length; i++) {
    final a = args[i];
    if (a == '--locales-dir' && i + 1 < args.length) {
      localesDir = args[++i];
      continue;
    }
    if (a == '--output' && i + 1 < args.length) {
      outputPath = args[++i];
      continue;
    }
    if (a == '--reference-locale' && i + 1 < args.length) {
      referenceLocale = args[++i];
      continue;
    }
    if (a == '--help' || a == '-h') {
      stdout.writeln(
        'Usage: dart run scripts/i18n/generate_getx_locales.dart \\',
      );
      stdout.writeln(
        '  --locales-dir <dir> --output <file> [--reference-locale en_GB]',
      );
      exit(0);
    }
  }

  if (localesDir == null || localesDir.isEmpty) {
    stderr.writeln('Missing --locales-dir');
    exit(2);
  }
  if (outputPath == null || outputPath.isEmpty) {
    stderr.writeln('Missing --output');
    exit(2);
  }

  return (
    localesDir: localesDir,
    outputPath: outputPath,
    referenceLocale: referenceLocale,
  );
}
